### ISSUE TITLE
Proposal: download Cypress to the common cached folder

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#1300]
## Feature

Instead of downloading and unzipping Cypress into `./node_modules/cypress/dist/` download it into a global folder for better caching. This will allow

- better caching of dependencies on CI
- reusing same version of Cypress if already downloaded once for some project

To determine output location use https://github.com/LinusU/node-cachedir

```js
var cachedir = require('cachedir')
var path = cachedir('cypress')
// `path` now contains the path under which you should store cached files
```

- cypress run, open, verify
  - [ ] ~take arg `--binary-folder` (looks like: `/foo/bar/Cypress.app` (macOS) or `/foo/bar/Cypress` (linux, win), to override default path to cypress binary folder (default is  `(cypressCache)/<cli version>/Cypress.app`)~
  - [x] can override folder of binary with env var `CYPRESS_BINARY_FOLDER=/path/to/Cypress.app`
    - [x] warn user if set

- cypress install
  - [x] Checks `(cypressCache)/<cli version>` for already installed binary folder (`Cypress.app` on macOS, `Cypress` on linux/win), and if binary version matches `(installVersion)`, do nothing.
  - [x] `(installVersion)` defaults to cli version, is overridden by env var `CYPRESS_BINARY_VERSION` during install
    - can be either `semvar: 1.2.3`, `url: www.cypress.io/download/1.2.3`, or `zip: /path/to/cypress.zip`
  - [x] if `cypress install --force`, force reinstall to `(cypressCache)/<cli version>`
  - [x] `(cypressCache)` defaults to:
    - `~/Library/Caches/Cypress` (macOS)
    - `~/.cache/Cypress` (linux)
    - `/AppData/Local/Cypress/Cache` (win)
  -  [x] `(cypressCache)` can be overridden with env var `CYPRESS_CACHE_DIRECTORY`
  - [x] before install, ensure write access to `(cypressCache)`

- [x] custom error message for failed access to `(cypressCache)`
- [ ] docs
  - [x] Installing Cypress
  - [ ] ~command line usage~
  - [ ] update info about global install
- [x] manual testing all use cases
  
  - [x] cypress install
    - CYPRESS_BINARY_VERSION
      - [x] url 
        - [x] skip if has any cache
      - [x] semvar
      - [x] zip
        - [x] skip if has any cache
        - [x] show progress for unzipping 
      - [x] --force
    - [x] --force
  - [x] ~--binary-folder~
    - [x] ~cypress run~
    - [x] ~cypress open~
    - [x] ~cypress verify~
    - [x] ~invalid~
  - [x] CYPRESS_CACHE_DIRECTORY
    - valid
    - invalid, error message
  

- [x] add local code coverage with `nyc`
  - [ ] ~~send to `coveralls` in CI~~
## Stretch goal
- [ ] can we cache `ffmpeg` separately to avoid bundling the same version over and over?

**Comment by ntwb** [comment]
Either this is a duplicate of #1233 or vice-versa, not overly concerned which issue is closed but they are for the most part duplicates

**Comment by EirikBirkeland** [comment]
The Cypress.io download always doubles the time my `yarn install` takes, on a 25 mbit connection. There are ways to get around, but would greatly appreciate caching.

**Comment by bahmutov** [comment]
Can you cache node_modules ?

**Comment by ncjones** [comment]
To work around this issue we build a docker image with our test suite's dependencies pre-installed.

**Comment by STCUSoftDev** [comment]
Would love to see this put into a global location.

**Comment by KellyR-STCU** [comment]
Would love to see this put into a global location

**Comment by EirikBirkeland** [comment]
@bahmutov I can cache node_modules on CI server, but for local builds we often change our dependencies because we are jumping between branches.

**Comment by garytryan** [comment]
Also having this problem with slow install times for local development using Yarn.

**Comment by Bkucera** [comment]
currently in progress in PR  #1582 

(my hard drive needed the space) --> ![image](https://user-images.githubusercontent.com/14625260/38759001-be13b914-3f41-11e8-8905-4149cf39c263.png)

**Comment by Bkucera** [comment]
This also enables us to ship our docker images with Cypress pre-cached, which will help simplify CI setup!

**Comment by brian-mann** [comment]
Yeah it's true but we'll need to update our build process to include it - but we should it's a good idea.

Open a separate issue for that and we can work on that while you finish this PR.

**Comment by bahmutov** [comment]
we need to think about caching Cypress in the docker container - because it takes up a lot of space. If we do second split (Electron vs our code), then YES, @Bkucera that would be super good idea to include multiple versions pre-cached because they would not add much weight

**Comment by brian-mann** [comment]
@bahmutov good point... that's another "+" in the corner of splitting out those two things vs caching the entire app bundle.

**Comment by maxime1992** [comment]
According to [Gleb's comment](https://github.com/cypress-io/cypress/issues/1300#issue-296488163), this issue should include:

> better caching of dependencies on CI
> reusing same version of Cypress if already downloaded once for some project

I just tried to:
- upgrade cypress within my project to 3.0
- make sure that `~/.cache/Cypress/3.0.0` exists
- `rm -rf node_modules`
- `yarn` again

Cypress has been downloaded again instead of using the local version, available in cypress global cache folder. Am I missing something? Is that not the expected behaviour and maybe I should open a new issue?

Looking forward to it, congrats :)

**Comment by Bkucera** [comment]
@maxime1992 yep, that's a bug, there's a fix ready to get merged in: https://github.com/cypress-io/cypress/pull/1819

**Comment by jeserkin** [comment]
If one installs it globally on machine and versions match, then installing with npm shouldn't pull it again and install on project level, correct?

**Comment by Bkucera** [comment]
@jeserkin correct

**Comment by jeserkin** [comment]
Is it possible, that installing dependencies with `npm ci`, somehow mitigates existence check and still downloads cypress based on project level description?
