### ISSUE TITLE
Unified Test Runner(s) GUI

### ISSUE THREAD

**Issue by lmiller1990** [cypress-io/cypress#16697]
Tracking some work for the updated unified desktop GUI. This ticket is for internal use by the Cypress team.

- [ ] Set up Windi CSS

- however you do that
- design system
- springboard → start here
- good if we have a nice way to reuse it everywhere else?

- [ ] Carousel

- carousel buttons component
- change state based on props

- [ ] Routing/Screen Workflow

- set up routing
- should have an appropriate interface to work with carousel
- "steps" abstractions
- some pages may not have the dots

Perhaps something like: 

```jsx
<Carousel>
    <Page> 
      {/* This is a react router route?? */}
    </Page>
  <Steps number={1} />
</Carousel>
```

- [ ] Button (Ghost/Secondary/Outline)

- improve button
- "basic" button prop
- this can be in the design system, but it could also just be in the springboard package and refactored later.

```jsx
<Button secondary={true} />
```

- [ ] Select your Tooling

- show a dropdown using `<select>` with all combinations (React, Next, Vue...)
    - libs (Vue, Next)
    - framework (Next, Nuxt)
    - Dev server (webpack/vite)

- [ ] Info Card Component

- on the third step
- it has a link

- [ ] Copy this Code Box

- make it. Fairly straight forward.
