### ISSUE TITLE
Support video capture in browsers other than headless electron 

### ISSUE THREAD

**Issue by Bkucera** [cypress-io/cypress#1767]
## Features
Video recording for both local and CI:

- [x] chrome headed in https://github.com/cypress-io/cypress/pull/4628 - released in 3.5.0
- [ ] electron headed in #6632
- [x] chrome headless in #5676 - released in 3.8.0 
- [x] firefox headed in #1359 - released in 4.0.0
- [x] firefox headless in #6336  - released in 4.0.0

## Tasks
- chrome headed:
  - use devTools protocol [`screenCast api`](https://chromedevtools.github.io/devtools-protocol/tot/Page/#method-startScreencast)
- electron headed:
  - use devTools protocol [`screenCast api`](https://chromedevtools.github.io/devtools-protocol/tot/Page/#method-startScreencast)
- chrome headless
  - use devTools protocol [`screenCast api`](https://chromedevtools.github.io/devtools-protocol/tot/Page/#method-startScreencast)
- firefox headed:
  - use `getUserMedia` API + user prefs to auto-accept prompt to capture current tab
- firefox headless:
  - use `getUserMedia` API + user prefs to auto-accept prompt to capture current tab

#### Related
Video record also mentioned in #745

**Comment by itaykotler-fundbox** [comment]
@Bkucera, is there a chance this feature will be resolved for the next version 3.0.2 or maybe 3.1.0?
I'de like to run my tests on headless chrome browser and be able to record the test runs.
Thanks

**Comment by Bkucera** [comment]
@itaykotler-fundbox certainly not in a patch release! This is a pretty big feature, we don't even have headless chrome support yet, so that will have to come before recording video on headless chrome, which isn't coming out in 3.1.0. Currently we are working on Native Events, Full Network Proxy support, and Firefox.

**Comment by itaykotler-fundbox** [comment]
@Bkucera, thanks for the response

**Comment by Bkucera** [comment]
@itaykotler-fundbox but do throw a :+1: on the top level comment to give the issue higher priority, we sort by reactions to determine what the community wants

**Comment by nickatnight** [comment]
Almost a year later..any update?

**Comment by mikhaildzarasovvineti** [comment]
Any updates here?

**Comment by haoyu-twins** [comment]
Any update?

**Comment by bahmutov** [comment]
Pull request https://github.com/cypress-io/cypress/pull/4628 has headed Chrome recording video of the test run. Waiting for final review, merge and release.

**Comment by robertaocanastrao** [comment]
Any news after the pull request?

**Comment by yelnar** [comment]
Waiting for this pr to be merged. We were forced to move to chrome browser because we needed WebGL support, and now when some of our tests fail, we do not have any videos.

**Comment by raylenmargono** [comment]
Any update?

**Comment by thiagobrez** [comment]
Wanting to know from this too. Any progress?

**Comment by drewwats** [comment]
Also patiently waiting due to WebGL issues on Electron...

**Comment by prudhvidandamudi** [comment]
Any updates for this issue!! planning to do a POC on cypress for our organization and videos are not supporting for chrome browser. The organization is expecting tests on chrome.

**Comment by bahmutov** [comment]
We are working on recording Chrome headed video in https://github.com/cypress-io/cypress/pull/4628 targeting v3.5.0 release

**Comment by jennifer-shehane** [comment]
We have been writing and reviewing this code since our last update. You can scroll to the bottom of any PR and see the exact activity that is happening https://github.com/cypress-io/cypress/pull/4628 - this one having been commented on 29 minutes ago. 

## Please do not comment for updates

Please refrain from commenting asking for updates 🙏 

1. It creates noise for other people watching progress here.
1. it takes the team's focus away from working on the PR.
1. You can find ALL current updates by scrolling to the bottom of the linked PR: https://github.com/cypress-io/cypress/pull/4628

**Comment by brian-mann** [comment]
I believe this is already done and released... yeah? 

/cc @Bkucera @flotwig

**Comment by jennifer-shehane** [comment]
@brian-mann The checklist in the description is accurate as of 3.8.2. So the ones that are not checked have not been delivered so this should not be released. 

You cannot record video in Electron headed, Firefox headless, Firefox headed as of 3.8.2.
