### ISSUE TITLE
Proposal: refactor logging, capture for dashboard recordings, output to file, serialize browser console logs

### ISSUE THREAD

**Issue by brian-mann** [cypress-io/cypress#2078]
More comprehensive proposal is needed but summary is this:

- [ ] Refactor existing debug / log implementation
- [ ] Create logger wrapper utility to manage all logic
- [ ] Route `debug`, `console.log` and `performance` data through this utility
- [ ] Enable silencing all node based `console.log` per https://github.com/cypress-io/cypress/issues/2071
- [ ] Capture browser console methods per https://github.com/cypress-io/cypress/issues/700
- [ ] Write all logs to an `output.log` per project in AppData 
- [ ] Persist logs on recorded dashboard runs
- [ ] Enable changing the logs folder via some CLI flag like `--logs-folder=/path/to/logs`
- [ ] Fix `morgan` output always appearing
- [ ] Expose a `pluginEvent` for `internal:log` perhaps
- [ ] Start capturing performance related data in logs

**Comment by jennifer-shehane** [comment]
Would this issue cover this request? https://github.com/cypress-io/cypress/issues/2991

**Comment by oghmjos** [comment]
As first step having feature to upload text files from logs directory to dashboard whould be very helpful and could be a good jumpstart. Will enhance cypress-failed-log plugin too with no extra effort. Maybe its already planned in the nearest future?

**Comment by jennifer-shehane** [comment]
Since this issue hasn't had activity in a while, we'll close this issue.

**Comment by jrr** [comment]
FYI this (closed) issue is still referenced from the FAQ:

https://docs.cypress.io/faq/questions/using-cypress-faq/#Can-I-print-the-list-of-commands-from-a-test-in-the-terminal

**Comment by jennifer-shehane** [comment]
@jrr Thanks, updating the docs.
