### ISSUE TITLE
Populate Public Triage Board Custom Data fields via github actions

### ISSUE THREAD

**Issue by nagash77** [cypress-io/cypress#25429]
The github project API currently does not allow us to track and more importantly report on these data points.  So we are going to use automation to set these fields manually for future use in reporting.

Fields to be automatically populated:

- [x] Status - this should be updated whenever an issue is moved into a specific status column on the board.
  - This is done automatically when moving an item
- [ ] Date Routed - We want to store the datetime when an issue FIRST entered the status of `Routed`
- [ ] Date Added to Triage Backlog - We want to capture the datetime of when an issue was first added to the public triage board project
- [ ] Date Closed - When an issue is moved to closed we want to capture that datetime. If an issue is reopened, this field should be cleared.
- [ ] Date First Responded - When a member of our github org comments on an issue for the first time, we want to capture that datetime.
- [ ] Date Reopened - When an issue goes from closed to open, we want to capture that datetime
