### ISSUE TITLE
Epic: Configuration and events overhaul

### ISSUE THREAD

**Issue by chrisbreiding** [cypress-io/cypress#2840]
This is an issue to track the work being done for [overhauling configuration and events](https://github.com/cypress-io/cypress/pull/4225). It includes numerous breaking changes.

* [x] Rename `plugins` to `background`
  - [x] Code - [Issue](https://github.com/cypress-io/cypress/issues/2285) - [PR](https://github.com/cypress-io/cypress/pull/2408)
  - [x] Docs - [Issue](https://github.com/cypress-io/cypress-documentation/issues/890) - [PR](https://github.com/cypress-io/cypress-documentation/pull/967)
  - [x] Example repos - [Issue/PRs](https://github.com/cypress-io/cypress/issues/2488)
* [x] Add background events that mirror driver events 
  - [x] Code - [Issue](https://github.com/cypress-io/cypress/issues/2283) - [PR](https://github.com/cypress-io/cypress/pull/2309)
  - [x] Docs - [Issue](https://github.com/cypress-io/cypress-documentation/issues/890) - [PR](https://github.com/cypress-io/cypress-documentation/pull/967)
* [x] Rename events - [Issue](https://github.com/cypress-io/cypress/issues/2838)
  - [x] Code - [Issue](https://github.com/cypress-io/cypress/issues/2283) - [PR](https://github.com/cypress-io/cypress/pull/2309)
  - [x] Docs - [Issue](https://github.com/cypress-io/cypress-documentation/issues/890) - [PR](https://github.com/cypress-io/cypress-documentation/pull/967)
* [x] Add new background events 
  - [x] Code - [Issue](https://github.com/cypress-io/cypress/issues/2286) - [PR](https://github.com/cypress-io/cypress/pull/2331)
  - [x] Docs - [Issue](https://github.com/cypress-io/cypress-documentation/issues/890) - [PR](https://github.com/cypress-io/cypress-documentation/pull/967)
* [x] Rename 'log:added' to 'internal:log' and 'log:changed' into 'internal:logChange' event 
  - [x] Code - [Issue](https://github.com/cypress-io/cypress/issues/2885) - [PR](https://github.com/cypress-io/cypress/pull/3313)
  - [x] Docs - [Issue](https://github.com/cypress-io/cypress-documentation/issues/1387) - [PR](https://github.com/cypress-io/cypress-documentation/pull/1404)
* [ ] Add `window:*` events 
  - [x] Code - [Issue](https://github.com/cypress-io/cypress/issues/2886) - [PR](https://github.com/cypress-io/cypress/pull/3529)
  - [x] Docs - [Issue](https://github.com/cypress-io/cypress-documentation/issues/1465) - [PR](https://github.com/cypress-io/cypress-documentation/pull/1512)
* [ ] Fix test hanging issue related to async errors
  - [ ] Code - [Issue](https://github.com/cypress-io/cypress/issues/3349)
* [ ] Add new event 'page:error' 
  - [x] Code - [Issue](https://github.com/cypress-io/cypress/issues/2884) - [PR](https://github.com/cypress-io/cypress/pull/3244)
  - [ ] Docs - [Issue](https://github.com/cypress-io/cypress-documentation/issues/1359)
* [ ] Remove `*load` callbacks from firing when only the hash changes 
  - [ ] Code - [Issue](https://github.com/cypress-io/cypress/issues/3155)
  - [ ] Docs - _Need Issue_
* [ ] Namespace internal events 
  - [ ] Code - [Issue](https://github.com/cypress-io/cypress/issues/2887)
  - [ ] Docs - [Issue](https://github.com/cypress-io/cypress-documentation/issues/1408)
* [ ] Update example repos - [Issue/PRs](https://github.com/cypress-io/cypress/issues/2488)

**Comment by jennifer-shehane** [comment]
Ran across this issue and thought it was in scope for 5.0 work - basically updating the comments of the scaffolded `plugins/index.js` file - to include more information about what's possible with new events. https://github.com/cypress-io/cypress/issues/1861

**Comment by jennifer-shehane** [comment]
Suggestion from user in https://github.com/cypress-io/cypress/issues/6946 to expose an event listener for when Cypress is about to exit the run completely.

**Comment by san-ouadghiri** [comment]
Will we be able to alter Cypress behavior on every events listed here ? https://docs.cypress.io/api/events/catalog-of-events.html#Examples

I would like to enhance the behavior we have when uncaught:exception is called (to log some additional data) without polluting every beforeEach nor migrating to cucumber (before hook).

**Comment by jennifer-shehane** [comment]
Closing due to inactivity

**Comment by WORMSS** [comment]
Open again due to activity.
