### ISSUE TITLE
Improve browser detection

### ISSUE THREAD

**Issue by flotwig** [cypress-io/cypress#3202]
For fixing/changing a variety of things relating to how browser detection is done.

## Improve existing browser detection
* [x] #1400 - PR: #3209 Linux browser detection doesn't work for Chromium
* [x] #3183 - PR: ~#3186~ #3225  - Linux browser detection doesn't work for Chromium as a snap (snap)
* [x] #3217 - PR: #3225 Manjaro binary names for Chromium, Chrome are not included
* [x] ~Include google-chrome-beta, google-chrome-unstable as possible browsers~
    * this works out of the box with --browser=/path/
* [x] #3218 - PR: #3225 - Represent browsers as `Browser` objects internally
    * this will permit adding the new functionality described throughout this issue
* [x] PR: #3225 - Add a way for multiple versions of the same browser to be detected and used alongside each other
    * for example, on Linux, google-chrome, google-chrome-beta, and google-chrome-unstable would be detected as Chrome 71, Chrome 72, and Chrome 73 at the time of this writing
    * current codebase uses the browser name to launch browsers, so all three of these would map to `chrome` and only Chrome 71 will be launched if you request to launch any of them
    * proposal: always execute the latest version found, if the user wants to use a different version, they can pass the exact path to it
    * ~proposal: allow users to specify `--browserVersion` command-line argument, then that specific version of the browser would be used; otherwise, use the latest version found by default:~
        *     cypress run --browser chrome --browserVersion 72 ## launches Chrome 72  
              cypress run --browser chrome ## launches Chrome 73

## Add ways for users to explicitly define browser
* [x] #1026 - PR: #3337 - Gleb had an issue for passing browser path in CLI args along with a pr #1037
    * `cypress run --browser /usr/bin/chromium`
    * Cypress will attempt to run `${browser} --version`, and then match stdout against the list of known browser `versionRegex`es defined in `browsers.ts`
    * If a match is found, we know what kind of browser it is and how to launch it
    * If no match is found, fail
* [x] ~Add a hook so that users can define browsers at runtime~
    * nixing for now unless we see a need
    * We already have a [hook so users can change browser arguments](https://docs.cypress.io/api/plugins/browser-launch-api.html#Usage), but not a hook for changing the actual browser used
    * proposed interface:
    ```ts
        type FoundBrowser = {
            name: string
            path: string
        }

        on('after:browser:detection', (foundBrowsers: FoundBrowser[]): FoundBrowser[] => {
            // user can modify foundBrowsers as they wish and return it
            foundBrowsers = [...foundBrowsers, {
                displayName: 'My Custom Chromium',
                path: '/usr/local/bin/crazy-chromium'
            }]
            // Cypress will still attempt to run `/usr/local/bin/crazy-chromium --version`
            // to extract version information and detect what type of browser it is
            return foundBrowsers
        })
    ```
* [x] ~Add configuration to cypress.json for adding additional browsers~
    * Accomplishes the same behavior as above, but statically:
    ```js
        {
            // ...cypress config here
            "additionalBrowsers": [
                {
                    "displayName": "Chromium X",
                    "windowsPath": "C:\\Program Files\\ChromiumX\\chrome.exe",
                    "binary": "chromium-x"
                }
            ]
        }
    ```

## Add documentation for how to find browser versions
 * [x] cypress-io/cypress-documentation#707 - PR: #3981 - Create an interface to help users find older Chrome versions
 * [x] cypress-io/cypress-documentation#1339 Add docs on how to run Chromium, Canary
 * [x] ~Add documentation for new plugin hook~
 * [x] cypress-io/cypress-documentation#1419 Add documentation for new command line arguments
 * [x] PR: cypress-io/cypress-documentation#1388 Maybe document how Cypress does browser detection internally, so that users understand why it doesn't always work
