### ISSUE TITLE
Cross Browser issue tracker

### ISSUE THREAD

**Issue by Bkucera** [cypress-io/cypress#3207]
Tracking issue for progress on #310

### Firefox _in progress_: 
- [x] firefox support PR:#1359
- [x] [post-release candidate] capture video with extension API/screencast API

### Microsoft Edge _in progress_:

- [x] Edge support PR https://github.com/cypress-io/cypress/pull/6181

### Chrome-headless _done_:
- [x] support chrome headless issue:#832 
- [x] capture video with screencast API #4791

**Comment by ianschmitz** [comment]
Should we include Edge in this list as well? Not sure how Edge fits in this list with the [recent announcement](https://blogs.windows.com/windowsexperience/2018/12/06/microsoft-edge-making-the-web-better-through-more-open-source-collaboration/) to switch to use Chromium under the hood.

**Comment by Bkucera** [comment]
@ianschmitz we currently haven't done any work towards Edge, but we'll update this with updates

**Comment by danieltisdale** [comment]
@Bkucera Hi Ben! Very eager to start using Cypress in the future once there is more cross browser support. Any plans to include Safari as well?

**Comment by ganqqwerty** [comment]
The fact that cypress is Chrome-only is the only limiting factor that we have to start using it.

**Comment by Bkucera** [comment]
@danieltisdale no progress specifically on safari, but the work we're doing for the other browsers should help lay the groundwork for supporting it in the future.

**Comment by bjowes** [comment]
Please reconsider supporting Edge!

IE11 is clearly the official browser within most large corporations, but as they are migrating to Windows 10 many are trying to replace IE11 with Edge as the official browser. Any E2E tools that have ambitions to be widely used in this market segment will have to support the major official browsers. With the current rate of progress, I am concerned that by the time Cypress actually supports IE11, Edge will have grown to be more important.

The current Edge browser is quite locked down. But if [the rumours regarding a future Edge version supporting Chrome plugins](https://www.theverge.com/2018/12/10/18134073/chromium-microsoft-browser-chrome-extensions-xbox-one) turn into reality, it would seem that adding support for Edge will be easier than support for IE11.

**Comment by johanneslumpe** [comment]
@Bkucera is there a more actionable list of things that need to be done except the one in the description? getting IE11 support working would be amazing and if there is stuff that can be done to help I'd be more than happy to give it a shot.

**Comment by johanneslumpe** [comment]
@bjowes Especially in government agencies it is very unlikely that IE11 is being replaced any time soon, so getting support there first seems like a good idea.

**Comment by DoctaCloak** [comment]
I second that @johanneslumpe.  Would love to jump in on this.

**Comment by TSangani** [comment]
@Bkucera - Do you have an ETA for IE11 Support?

**Comment by YOU54F** [comment]
Chromium based Microsoft edge was released yesterday on insiders

https://www.microsoftedgeinsider.com/en-us/download/

would be cool to see if this works with Cypress, if I get some time, I might have a go

**Comment by a4xrbj1** [comment]
@Bkucera - any update on the progress? I second that the lack of any other browser support other than Chrome is a big downside for Cypress.

**Comment by jennifer-shehane** [comment]
In order to offer cross-browser support, we first need to support [native events](https://github.com/cypress-io/cypress/issues/311). We also need to deliver all the features listed in this cross-browser tracking issue. 

There is a lot of discovery involved in this process, so this is the closest estimation we can give - the more checkmarks we check off, the closer we are to delivering cross-browser support.

**Comment by johanneslumpe** [comment]
@jennifer-shehane Just to be clear: this means that you do not require/want community support on this, correct?

**Comment by jennifer-shehane** [comment]
@johanneslumpe Collaboration can be quite difficult since a lot of this is hands on. But, the todo list is published and the PRs are public. Reviewing PR work is always helpful. 
- https://github.com/cypress-io/cypress/pull/2436

The branches with work are also published here.

**Comment by VSinghhh** [comment]
@jennifer-shehane you wrote
"There is a lot of discovery involved in this process, so this is the closest estimation we can give - the more checkmarks we check off, the closer we are to delivering cross-browser support."

I may have missed the estimation; but I would appreciate if you could provide the estimate when this is expected to work.

We are in the process of implementing automation test we previously had using selenium (java) and are happy to go with cypress but working with government clients means that IE11 compatibility is a must (and therefore that our tests execute on IE11). So far our experience with cypress has been really good (kudos on the fantastic job!), but sadly this is a bit of a dealbreaker for us as we have a very slim chance in changing the customers preset browser.

Would appreciate a rough estimation (and if the expectation is that it will take a few days, weeks or months, that's fine.... we'll be able to choose framework based on that).

**Comment by mightyiam** [comment]
@VSinghhh, I'm pretty sure that what @jennifer-shehane means regarding estimation, is that the estimation is not a time-frame, but the checklist itself. The checklist at the description of this issue.

**Comment by YOU54F** [comment]
So chromium based MSEdge was leaked for macosx

https://officecdn.microsoft.com/pr/C1297A47-86C4-4C1F-97FA-950631F94777/MacAutoupdate/MicrosoftEdgeCanary-76.0.151.0.pkg

Downloaded and then renamed package to not have spaces in it, as cypress would throw this error

```
➜ npx cypress run --browser /Applications/Microsoft\ Edge\ Canary.app/Contents/MacOS/Microsoft\ Edge\ Canary
We could not identify a known browser at the path you provided: `/Applications/Microsoft Edge Canary.app/Contents/MacOS/Microsoft Edge Canary`

The output from the command we ran was:

 Command failed: /bin/sh -c /Applications/Microsoft Edge Canary.app/Contents/MacOS/Microsoft Edge Canary --version
/bin/sh: /Applications/Microsoft: No such file or directory

```

After renaming the path, I got

```
➜  npx cypress run --browser /Applications/MSEdge.app/Contents/MacOS/MicrosoftEdgeCanary
We could not identify a known browser at the path you provided: `/Applications/MSEdge.app/Contents/MacOS/MicrosoftEdgeCanary`

The output from the command we ran was:

 Microsoft Edge 76.0.158.0 Canary
```

Need to check where the browser list is, to see if I can force it to recognise edge.

**Comment by flotwig** [comment]
@YOU54F The browser list is here: https://github.com/cypress-io/cypress/blob/d4d7326ebb5529bf9209ed32b4b85a63689083e0/packages/launcher/lib/browsers.ts#L6

Add Edge with "family: 'chrome'". I don't think it will work that easily, but maybe :)

**Comment by YOU54F** [comment]
@flotwig - worked better than expected! not bad for first time runs!

<img width="166" alt="Screenshot 2019-05-14 at 22 59 23" src="https://user-images.githubusercontent.com/19932401/57735837-dfe85880-769d-11e9-98a2-8e36e2042087.png">
<img width="807" alt="Screenshot 2019-05-14 at 22 59 28" src="https://user-images.githubusercontent.com/19932401/57735839-e080ef00-769d-11e9-9317-f154b4463bff.png">
<img width="1208" alt="Screenshot 2019-05-14 at 23 11 03" src="https://user-images.githubusercontent.com/19932401/57735840-e080ef00-769d-11e9-885a-c97cf753a08e.png">
<img width="830" alt="Screenshot 2019-05-14 at 23 25 12" src="https://user-images.githubusercontent.com/19932401/57736409-bcbea880-769f-11e9-93d8-1d1d79d81445.png">
<img width="1920" alt="Screenshot 2019-05-14 at 23 26 02" src="https://user-images.githubusercontent.com/19932401/57736410-bcbea880-769f-11e9-86d2-7d89638cff65.png">
<img width="1920" alt="Screenshot 2019-05-14 at 23 26 12" src="https://user-images.githubusercontent.com/19932401/57736411-bcbea880-769f-11e9-99d0-8e3ffef965e2.png">

**Comment by flotwig** [comment]
@YOU54F that's pretty awesome! What was broken, if anything?

**Comment by bahmutov** [comment]
Wait - is this the new Edge running tests?!!!

**Comment by YOU54F** [comment]
@flotwig seems pretty kushdi out the box

@bahmutov is it indeed sir!

written up a [blog post here](https://you54f.wordpress.com/2019/05/15/the-new-chromium-based-microsoft-edge-for-mac-has-been-leaked%e2%80%8a-%e2%80%8aand-it-works-with-cypress/)

**Comment by bahmutov** [comment]
Omg you are our hero, Yousaf, mad respect, blog and we will retweet it a lot

**Comment by YOU54F** [comment]
Hahaha no worries matey, got loads of respect for the hard work you lot are doing. (I actually follow you on here because every single Cypress repo I go to, you've had your hand in haha!)

I've posted it up on twitter here

https://twitter.com/YOU54F/status/1128451445697728517

**Comment by jtmorrisbytes** [comment]
Hello everyone! firstly I want to say I really like cypress. I would like to see this tool reach other browsers if possible. I was wondfering if there was any way I could help get native events working.

**Comment by BenLevy1138** [comment]
I'm already set up to do cross-browser testing as well as some limited cross-platform testing, which I think is something we should be considering as well (i.e. we don't want to find ourselves in a situation where we discover after releasing to production that firefox and chrome work great as long as they're being run on an up-to-date, linux-like machine). We've got a pretty clear roadmap for expanding those capabilities, it's just a matter of time and will.  

Another, related question we should be thinking about is how far back we want to test against older browser versions and legacy OS's. In my experience, it's been extremely valuable to make a decision in advance, based on some combination of customer needs and practical considerations. 

From a testing/product perspective,  the question would be, what's the cut off where we would say to a customer that they need to update or standardize their browsers, their OS's or etc. in order for us to be able guarantee support. IE11 is a good example, and one that's been mentioned above. The cost of developing a product that's compatible with any pre-IE11 version of Explorer generally does not cover the benefit of gaining the subset of users that still run IE7 (or whatever). Making that limitation an explicit feature of our product offerings simplifies development and testing massively and being thoughtful about those kinds of things is ultimately gonna be more productive than trying to anticipate ever increasingly exotic edge-cases even where that forces our sales team to say that there are some limitations to the solutions we offer... in my humble opinion.

**Comment by icfantv** [comment]
> ...what's the cut off where we would say to a customer that they need to update or standardize their browsers, their OS's or etc. in order for us to be able guarantee support[?]

@BenLevy1138 The answer to that question is, unfortunately, highly subjective based on a given company and a given customer.  E.g.  if one paying customer requires IE11, but they represent a small fraction of your overall user base, it's almost certainly not worth it.  But if just one of your paying customers has 1m+ employees using your platform, you cannot just say "oh, we need you to upgrade your browser."

IT rollouts for something like this can literally take years of planning.  Historically, companies have spent millions of dollars building custom, in-house applications to work on specific platforms/browsers (read: IE6) and getting them off of that is akin to moving a mountain.

**Comment by oflores2313** [comment]
Any update on where cross browser functionality stands?  My company is looking to implement a new e2e framework but cross browser functionality is a big factor.

**Comment by scottwarren** [comment]
> Any update on where cross browser functionality stands? My company is looking to implement a new e2e framework but cross browser functionality is a big factor.

The status is in the [OP](https://github.com/cypress-io/cypress/issues/3207#issue-402426547)

**Comment by dono-greeff** [comment]
> > Any update on where cross browser functionality stands? My company is looking to implement a new e2e framework but cross browser functionality is a big factor.
> 
> The status is in the [OP](https://github.com/cypress-io/cypress/issues/3207#issue-402426547)

I think that was a find another solution as this is nowhere near close :P Last edit was January!

**Comment by lithqube** [comment]
> > > Any update on where cross browser functionality stands? My company is looking to implement a new e2e framework but cross browser functionality is a big factor.
> > 
> > 
> > The status is in the [OP](https://github.com/cypress-io/cypress/issues/3207#issue-402426547)
> 
> I think that was a find another solution as this is nowhere near close :P Last edit was January!

Hope this one comes sometime over this year 🧐

**Comment by dono-greeff** [comment]
> > > > Any update on where cross browser functionality stands? My company is looking to implement a new e2e framework but cross browser functionality is a big factor.
> > > 
> > > 
> > > The status is in the [OP](https://github.com/cypress-io/cypress/issues/3207#issue-402426547)
> > 
> > 
> > I think that was a find another solution as this is nowhere near close :P Last edit was January!
> 
> Hope this one comes sometime over this year 🧐

I for one am not holding my breath. I have gone with a different approach using an AI front end automation tool.

**Comment by a4xrbj1** [comment]
Which one? Not holding my breath either

**Comment by serdaryesilmurat** [comment]
Cross browser functionality is a must for our company. Is there any alternative to Cypress to achieve that? Has anyone used CodeceptJS which provides a generic BDD style syntax over several tools like Selenium WebDriver, Protractor, Puppeteer etc.?

**Comment by Bkucera** [comment]
Hi everyone, just updated the top-level to point to the relevant PRs on cross-browser support. Firefox #1359 is next up for release with only 15/3000 tests failing on that branch. 

We've taken our time to be diligent about common-denominator features to avoid excessive breaking releases or deprecating APIs in wake of cross-browser support. Thank you all for your patience and look out for the merge of #1359 for Cypress Firefox support.

**Comment by ryan-snyder** [comment]
@Bkucera If there's anything I can do in regards to this, let me know! I would love to help when/where I can. After I get a couple of other issues done, of course

**Comment by icfantv** [comment]
@serdaryesilmurat We've been using Selenium/Chauffeur and it's proven to be somewhat slow/flaky (although that's just as much on us as it is the product).  We have to support IE11 and use SauceLabs but that, too, is quite slow and flaky so we've built our own AMIs for running in-house.  Our teams/orgs that are using Cypress speak quite highly of it and from my observations, it's quite well-deserved.

We've started moving towards TestCafé with a decent degree of success.  Briefly, what the Cypress API has in terms of being robust and well-though, TestCafé lacks in certain areas.  It's simple and some of the design is not quite intuitive.  However, our use case is somewhat unique and TestCafé does handle page interactions well.

All in all, I wouldn't say I love TestCafé, but it does fill a need that Cypress currently does not and my org's leadership felt (and I somewhat concur) that it's too risky to rely simply and solely on a product roadmap.  Is there a discussion to be had about requiring test parity across browsers?  Sure.  However, we've been burned before by untested, cross-browser failures that weren't caught until production.

As @ryan-snyder offered above, I've reached out to @bahmutov to see what the plan is for cross-browser support and on what time frame but have not yet heard back.  I currently can't promise dedicated resources, but doing so becomes a lot easier to sell to leadership if we were to know there was momentum at the project-level in this area.

**Comment by dono-greeff** [comment]
> Which one? Not holding my breath either
> […](#)

Wanted to keep competition out of their issue thread but others have so why not then :P mabl.com check it out. Its really stable, fast and easy to script. For my team its great as we need to concentrate on our API's and lower levels. This frees up the time that used to get soaked up by maintenance etc.

**Comment by flotwig** [comment]
@icfantv @Bkucera is actively working on it and posted an update above your comment: https://github.com/cypress-io/cypress/issues/3207#issuecomment-535962564

**Comment by icfantv** [comment]
@flotwig Yes, I saw that, thanks.  The way I read it was that it was for Firefox only?  Was that not correct?

**Comment by Bkucera** [comment]
@icfantv I had updated the top-level with that link to open PRs about cross-browser:

>  just updated the top-level to point to the relevant PRs on cross-browser support.

**Comment by icfantv** [comment]
@Bkucera thanks!

**Comment by ale-grosselle** [comment]
Hi guys, 
me and some of my colleagues are considering cypress.io and other similar tools.
Cypress.io we like a lot, but for us it is essential to test the features on Safari and IE11.

Could you give to us an indicative ETA? For us it would be very important.

thank you very much!

**Comment by tomkel** [comment]
You all should give out an ETA in exchange for a large donation :)

**Comment by infomaven** [comment]
> @bjowes Especially in government agencies it is very unlikely that IE11 is being replaced any time soon, so getting support there first seems like a good idea.

That would also include healthcare clients.

**Comment by andrewmclagan** [comment]
Can we lock this thread down? I don’t know what the merits are of discussing IE11 market penetration. I’m guessing allot of devs have notifications on allot of issues this chat creates noise

**Comment by brettz9** [comment]
Looks like the checkbox for #832 can be marked with the issue now closed (?)

**Comment by cayleyh** [comment]
Echoing what others have said: would love to use Cyprus for work, but cannot justify it until there is support for Safari. 60%+ of our traffic for our websites and apps comes from mobile, and 60-70% of that is Mobile Safari. Safari & Mobile Safari are different enough from chrome (ie. our test suites contains enough breaking behavioural differences) that we cannot move to something that doesn't support it :(

**Comment by brettz9** [comment]
Just in case this may have any bearing: https://github.com/microsoft/playwright

**Comment by jennifer-shehane** [comment]
We are still actively working on releasing Firefox support. Currently the release is blocked by a garbage collection issue that causes Firefox to crash during some tests during `cypress run`. We're working with the Firefox team and also trying several creative workarounds to prevent the crashing. https://github.com/cypress-io/cypress/pull/1359

We are also working on releasing support for Microsoft Edge as part of this PR. https://github.com/cypress-io/cypress/pull/6181

They are currently targeted for the same release.

**Comment by amirrustam** [comment]
All browsers referenced in this issue are now supported. This is reflected in #310.

New issues will be created for supporting other browsers.
