### ISSUE TITLE
Cypress v4.0

### ISSUE THREAD

**Issue by chrisbreiding** [cypress-io/cypress#4270]
This is an issue to track the work being done for Cypress 4.0

* [x] Upgrade Mocha to 6.2.2
  - [x] Code - [Issue](https://github.com/cypress-io/cypress/issues/2528) - [PR](https://github.com/cypress-io/cypress/pull/2703)
  - [x] Docs - [Issue](https://github.com/cypress-io/cypress-documentation/issues/1077) - [PR](https://github.com/cypress-io/cypress-documentation/pull/1105)
* [x] Upgrade sinon to 7.5.0
  - [x] Code - [Issue](https://github.com/cypress-io/cypress/issues/2866) - [PR](https://github.com/cypress-io/cypress/pull/2881)
  - [x] Docs - [Issue](https://github.com/cypress-io/cypress-documentation/issues/890) - [PR](https://github.com/cypress-io/cypress-documentation/pull/967)
* [x] Upgrade Chai to 4.2.0
  - [x] Code - [Issue](https://github.com/cypress-io/cypress/issues/2529) - [PR](https://github.com/cypress-io/cypress/pull/2862)
  - [x] Docs - [Issue](https://github.com/cypress-io/cypress-documentation/issues/890) - [PR](https://github.com/cypress-io/cypress-documentation/pull/967)
* [x] cy.writeFile yields null
  - [x] Code - [Issue](https://github.com/cypress-io/cypress/issues/2466) - [PR](https://github.com/cypress-io/cypress/pull/2731)
  - [x] Docs - [Issue](https://github.com/cypress-io/cypress-documentation/issues/1116) - [PR](https://github.com/cypress-io/cypress-documentation/pull/1117)
* [x] Drop Node 4 & 6 support from CLI
  - [x] Code - [Issue](https://github.com/cypress-io/cypress/issues/4200) - [PR](https://github.com/cypress-io/cypress/pull/4208)
* [x] Upgrade browserify preprocessor / drop support for CJSX
  - [x] Code - [Issue](https://github.com/cypress-io/cypress/issues/3469) - [PR](https://github.com/cypress-io/cypress/pull/4308)
  - [x] Docs - [Issue](https://github.com/cypress-io/cypress-documentation/issues/1717) - [PR](https://github.com/cypress-io/cypress-documentation/pull/1718)
* [x] Docs - [Issue](https://github.com/cypress-io/cypress-documentation/issues/1709) - [PR](https://github.com/cypress-io/cypress-documentation/pull/1710)

**Comment by rodrigok** [comment]
Any date for the release?

**Comment by jennifer-shehane** [comment]
The plan at the moment is to release this alongside Firefox browser support, which is blocked by a memory issue that we're working with the Firefox team on diagnosing.  https://github.com/cypress-io/cypress/pull/1359
